openapi: "3.0.0"

info:
  title: Lunch Helper
  version: "0.1"

paths:
  /:
    get:
      summary: Main page
      description: Get main page
      operationId: lunch.api.get_main_page
      responses:
        200:
          description: Successfully loaded html page.
          content:
            text/html:
              schema:
                type: string

  /static/{filename}:
    get:
      summary: Static files
      description: Get static file.
      operationId: lunch.api.get_static_file
      parameters:
        - in: path
          name: filename
          description: File name.
          schema:
            type: string
      responses:
        200:
          description: Successfully returned static file.
        404:
          description: File not found.

  /api/restaurants:
    get:
      summary: Restaurants
      description: Get list of restaurants.
      operationId: lunch.api.get_restaurants
      responses:
        200:
          description: List of restaurants.
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurants:
                    type: array
                    items:
                      type: object
                      properties:
                        label:
                          type: string
                        name:
                          type: string
                        url:
                          type: string
                      required:
                        - label
                        - name
                        - url
                required:
                  - restaurants

  /api/menus:
    get:
      summary: Menus
      description: Get menus for requested restaurants and date.
      operationId: lunch.api.get_menus
      parameters:
        - in: query
          name: day
          description: Get menus for requested day.
          example: 2019-01-01
          schema:
            type: string
        - in: query
          name: restaurants
          description: List of restaurants.
          schema:
            type: string
      responses:
        200:
          description: Get menus for requested restaurants and date.
          content:
            application/json:
              schema:
                type: object
                properties:
                  day:
                    type: string
                  menus:
                    type: array
                    items:
                      type: object
                      properties:
                        restaurant:
                          type: string
                        menu:
                          type: string
                          nullable: true
                      required:
                        - restaurant
                        - menu
                required:
                  - day
                  - menus
        400:
          description: Invalid day format.
