name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
      REPO: jdobes/lunch
      PLATFORM: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build React app
        run: |
          ./build_web.sh
      - name: Install qemu-user-static for multi-arch build
        run: |
          sudo apt update && sudo apt install -y qemu-user-static
      - name: Login to registry
        run: |
          echo "$REGISTRY_PASS" | podman login -u "$REGISTRY_USER" --password-stdin "$REGISTRY"
      - name: Build image
        run: |
          podman build -f ./Dockerfile --platform "$PLATFORM" --manifest lunch .
      - name: Push image
        run: |
          podman manifest push --all lunch docker://$REGISTRY/$REPO:$(git rev-parse --short HEAD)
